name: remon_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.6"
  flutter_riverpod: "2.4.3"
  riverpod_annotation: "2.2.0"
  easy_localization: "3.0.3"
  go_router: "11.1.2"
  freezed_annotation: "2.4.1"
  json_annotation: "4.8.1"
  loading:
    git:
      url: https://github.com/adnanjpg/loading.git
  life_saver_extensions:
    git:
      url: https://github.com/adnanjpg/life_saver_extensions.git
  firebase_core_platform_interface: "4.8.0"
  firebase_core: "2.17.0"
  firebase_messaging: "14.6.9"
  shared_preferences: "2.2.1"
  uuid: "3.0.6"
  logger: "2.0.2+1"
  modal_bottom_sheet: "3.0.0-pre"
  dio: "5.3.3"
  remixicon: "1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "2.0.3"
  freezed: "2.3.5"
  build_runner: "2.4.6"
  json_serializable: "6.7.1"
  flutter_native_splash: "2.3.3"
  flutter_launcher_icons: "0.13.1"
  flutter_gen_runner: "5.3.2"
  riverpod_generator: "2.2.3"
  custom_lint: "0.4.0"
  riverpod_lint: "1.3.2"
flutter:
  uses-material-design: true
flutter_gen:
  output: lib/gen/
  line_length: 80
