name: remon_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  # caret syntax fixes a lot of warnings
  # https://github.com/dart-lang/sdk/issues/52672
  sdk: "^3.3.0"
dependencies:
  # 3.19.2
  # do not specify under the version under
  # the `flutter` item, as it is causing a problem
  # execute `fvm use 3.19.2` to use this version
  # when you want to upgrade, don't forget to update
  # codemagic.yaml
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.6"
  flutter_riverpod: "2.4.10"
  riverpod_annotation: "2.3.4"
  easy_localization: "3.0.5"
  go_router: "6.0.1"
  freezed_annotation: "2.4.1"
  json_annotation: "4.8.1"
  loading:
    git:
      url: https://github.com/adnanjpg/loading.git
  life_saver_extensions:
    git:
      url: https://github.com/adnanjpg/life_saver_extensions.git
  firebase_core_platform_interface: "5.0.0"
  firebase_core: "2.25.5"
  firebase_messaging: "14.7.17"
  shared_preferences: "2.2.2"
  uuid: "4.3.3"
  styled_text: "8.1.0"
  logger: "2.0.2+1"
  app_tracking_transparency: "2.0.4"
  dio: "5.4.1"
  mime: "1.0.5"
  http_parser: "4.0.2"
  widgetbook_annotation: "3.1.0"
  widgetbook: "3.7.1"
  remixicon: "1.1.1"
  google_fonts: ^4.0.4
  isar: "4.0.0-dev.14"
  isar_flutter_libs: "4.0.0-dev.14"
  path_provider: "2.1.2"
  flutter_slidable: "3.0.1"
  otp: "3.1.4"
  mobile_scanner: "4.0.1"
  chart_sparkline: "1.0.15+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "2.0.3"
  freezed: "2.4.7"
  build_runner: "2.4.8"
  json_serializable: "6.7.1"
  test: "1.24.9"
  flutter_native_splash: "2.3.1"
  flutter_launcher_icons: "0.13.1"
  flutter_gen_runner: "5.4.0"
  riverpod_generator: "2.3.11"
  custom_lint: "0.6.2"
  riverpod_lint: "2.3.9"
  widgetbook_generator: "3.7.0"
  very_good_analysis: "5.1.0"
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_gen:
  output: lib/gen/
  line_length: 80
