name: remon_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  # caret syntax fixes a lot of warnings
  # https://github.com/dart-lang/sdk/issues/52672
  sdk: "^3.1.4"
dependencies:
  # 3.13.8
  # do not specify under the version under
  # the `flutter` item, as it is causing a problem
  # execute `fvm use 3.13.8` to use this version
  # when you want to upgrade, don't forget to update
  # codemagic.yaml
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: "2.3.6"
  riverpod_annotation: "2.1.1"
  easy_localization: ^3.0.1
  go_router: ^6.0.1
  freezed_annotation: "2.2.0"
  json_annotation: "4.8.1"
  html_editor_enhanced: ^2.2.0+1-dev.1
  loading:
    git:
      url: https://github.com/adnanjpg/loading.git
  life_saver_extensions:
    git:
      url: https://github.com/adnanjpg/life_saver_extensions.git
  firebase_core_platform_interface: "4.8.0"
  firebase_core: "2.13.1"
  cloud_firestore: "4.4.3"
  cloud_functions: "4.0.11"
  firebase_messaging: "14.2.5"
  flutter_widget_from_html_core: ^0.9.1
  calendar_view: ^1.0.2
  shared_preferences: ^2.0.17
  uuid: ^3.0.7
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  # country_picker: ^2.0.19
  country_picker:
    # this package has a problem as it is filling the ui
    # and not respecting the constraints.
    # i've forked it and fixed it and submitted a PR.
    # until it is merged, use this forked version.
    # https://github.com/Daniel-Ioannou/flutter_country_picker/pull/108
    git:
      url: https://github.com/adnanjpg/flutter_country_picker.git
      ref: ui-filling-fix
  connectivity_plus: ^3.0.2
  styled_text: "8.1.0"
  flutter_local_notifications: "13.0.0"
  logger: ^1.2.2
  device_info_plus: ^8.1.0
  app_tracking_transparency: "2.0.3"
  google_sign_in: ^6.1.0
  font_awesome_flutter: "10.4.0"
  modal_bottom_sheet: "3.0.0-pre"
  dio: "5.3.2"
  mime: "1.0.4"
  http_parser: "4.0.2"
  widgetbook_annotation: ^3.0.0
  widgetbook: ^3.2.0
  remixicon: "1.0.0"
  custom_sliding_segmented_control: "1.8.0"
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  mobkit_dashed_border: "0.0.5"
  infinite_scroll_pagination: ^4.0.0
  google_fonts: ^4.0.4
  isar: "4.0.0-dev.14"
  isar_flutter_libs: "4.0.0-dev.14"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: "2.3.5"
  build_runner: ^2.4.6
  json_serializable: "6.7.0"
  test: ^1.22.0
  flutter_native_splash: "2.3.1"
  flutter_launcher_icons: "0.13.1"
  flutter_gen_runner: "5.2.0"
  riverpod_generator: "2.2.3"
  custom_lint: "0.4.0"
  riverpod_lint: "1.3.2"
  widgetbook_generator: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_gen:
  output: lib/gen/
  line_length: 80
